// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "acl-challenge/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, n
func (_m *MockNotificationRepository) Create(ctx context.Context, n *entity.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - n *entity.Notification
func (_e *MockNotificationRepository_Expecter) Create(ctx interface{}, n interface{}) *MockNotificationRepository_Create_Call {
	return &MockNotificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, n)}
}

func (_c *MockNotificationRepository_Create_Call) Run(run func(ctx context.Context, n *entity.Notification)) *MockNotificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Notification))
	})
	return _c
}

func (_c *MockNotificationRepository_Create_Call) Return(_a0 error) *MockNotificationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Notification) error) *MockNotificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockNotificationRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotificationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockNotificationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockNotificationRepository_Delete_Call {
	return &MockNotificationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockNotificationRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockNotificationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotificationRepository_Delete_Call) Return(_a0 error) *MockNotificationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockNotificationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function with given fields: ctx, userID
func (_m *MockNotificationRepository) FindAllByUserID(ctx context.Context, userID string) ([]entity.Notification, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []entity.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Notification, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Notification); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type MockNotificationRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockNotificationRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}) *MockNotificationRepository_FindAllByUserID_Call {
	return &MockNotificationRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID)}
}

func (_c *MockNotificationRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockNotificationRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotificationRepository_FindAllByUserID_Call) Return(_a0 []entity.Notification, _a1 error) *MockNotificationRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string) ([]entity.Notification, error)) *MockNotificationRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockNotificationRepository) FindByID(ctx context.Context, id string) (*entity.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockNotificationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockNotificationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockNotificationRepository_FindByID_Call {
	return &MockNotificationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockNotificationRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockNotificationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotificationRepository_FindByID_Call) Return(_a0 *entity.Notification, _a1 error) *MockNotificationRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entity.Notification, error)) *MockNotificationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, n
func (_m *MockNotificationRepository) Update(ctx context.Context, n *entity.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNotificationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - n *entity.Notification
func (_e *MockNotificationRepository_Expecter) Update(ctx interface{}, n interface{}) *MockNotificationRepository_Update_Call {
	return &MockNotificationRepository_Update_Call{Call: _e.mock.On("Update", ctx, n)}
}

func (_c *MockNotificationRepository_Update_Call) Run(run func(ctx context.Context, n *entity.Notification)) *MockNotificationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Notification))
	})
	return _c
}

func (_c *MockNotificationRepository_Update_Call) Return(_a0 error) *MockNotificationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Notification) error) *MockNotificationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
